version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "package-lock.json" }}
      - run:
          name: Install Node dependencies
          command: |
            npm install
      - save_cache:
          paths:
            - node_modules
          key: deps-{{ checksum "package-lock.json" }}
      - run:
          name: Run build script
          command: |
            npm run build
      - persist_to_workspace:
          root: ~/
          paths:
            - project/build

  test:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "package-lock.json" }}
      - run:
          name: Install Node dependencies
          command: |
            npm install
      - run:
          name: Execute unit tests
          command: |
            npm run test

  scan:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "package-lock.json" }}
      - run:
          name: Install Node dependencies
          command: |
            npm install
      - run:
          name: Scan for critical vulnerabilities
          command: |
            npm run scan

  deploy:
    docker:
      - image: cimg/aws:2022.11
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Sync build folder with S3 Bucket
          command: |
            aws s3 sync ~/project/build s3://$S3_BUCKET_NAME

workflows:
  default:
    jobs:
      - build
      - test:
          requires:
            - build
      - scan:
          requires:
            - build
      - deploy:
          requires:
            - test
            - scan
