version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: |
            npm install
      - save_cache:
          paths:
            - node_modules
          key: deps-{{ checksum "package-lock.json" }}
      - run:
          name: Generate Production Build
          command: |
            npm run build

  test:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Execute Unit Tests
          command: |
            npm run test

  scan:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Scan for vulnerabilities
          command: |
            npm run scan

workflows:
  default:
    jobs:
      - build
      - test:
          requires:
            - build
      - scan:
          requires:
            - build
